name: nornir

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nornir-backend
    env_file:
      - .env
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nornir-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
